import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalBreadcrumb from "@/components/global-breadcrumb";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "It's Me, Francis!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute top-0 left-0 right-0 text-center">
          <div className="absolute top-30 left-6 z-40">
            <div className="shadow-xl
                            font-medium 
                            text-base
                            border-3xl
                            bg-white
                            hover:shadow-2xl 
                            transition-shadow 
                          ">
              </div>
              <GlobalBreadcrumb />
            </div>

            {/* Page Content */}
            {children}
          </div>
          </body>
        </html>
        );
}
